#!/usr/bin/env node
// SECURITY MANIFEST:
//   Environment variables accessed: MARKETPLACE_BASE_URL (only)
//   External endpoints called: {BASE}/upload/image, {BASE}/jobs/:jobId/bids
//   Local files read: ~/.openclaw/marketplace-config.json, /tmp/marketplace_pending.json
//   Local files written: /tmp/marketplace_result_*, /tmp/preview_* (auto-deleted)

'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');
const { execFileSync } = require('child_process');

const CONFIG_PATH  = path.join(os.homedir(), '.openclaw/marketplace-config.json');
const SKILL_DIR    = path.join(os.homedir(), '.openclaw/skills/agent-task-marketplace');
const PENDING_PATH = '/tmp/marketplace_pending.json';
const BASE_URL     = process.env.MARKETPLACE_BASE_URL || 'http://localhost:3000';

const jobId = process.argv[2];
if (!jobId) {
  console.error('Usage: approve.js <jobId>');
  process.exit(1);
}

// ─── Notify helper ────────────────────────────────────────────────────────
function notify(type, payload = {}) {
  process.stdout.write(JSON.stringify({ type, ts: new Date().toISOString(), ...payload }) + '\n');
  process.stderr.write(`[${type}] ${payload.message || ''}\n`);
}

// ─── Load config + pending ────────────────────────────────────────────────
let config;
try {
  config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
} catch (err) {
  notify('MARKETPLACE_ERROR', { message: `Failed to read config: ${err.message}` });
  process.exit(1);
}

let pending;
try {
  pending = JSON.parse(fs.readFileSync(PENDING_PATH, 'utf-8'));
} catch (err) {
  notify('MARKETPLACE_ERROR', { message: `Failed to read pending jobs: ${err.message}` });
  process.exit(1);
}

const entry = pending[jobId];
if (!entry) {
  notify('MARKETPLACE_ERROR', { jobId, message: `❌ No pending job found for ID: ${jobId}` });
  process.exit(1);
}

const job         = entry.job;
const budget      = job.spec?.budget ?? 0;
const desc        = job.spec?.description || '';
const category    = job.spec?.style || job.spec?.purpose || 'unknown';
const resultPath  = `/tmp/marketplace_result_${jobId}`;
const previewPath = `/tmp/preview_${jobId}`;

notify('MARKETPLACE_PROCESS_START', {
  jobId, category, budget,
  message: `⚙️ Starting bid process for Job #${jobId} (${category} / ${budget})`
});

function cleanup() {
  if (fs.existsSync(resultPath)) fs.unlinkSync(resultPath);
  if (fs.existsSync(previewPath)) fs.unlinkSync(previewPath);
}

try {
  // Step 1 — Generate result
  notify('MARKETPLACE_PROCESS_STEP', {
    jobId, step: 1, total: 4,
    message: `⚙️ [1/4] Generating result...`
  });
  fs.writeFileSync(resultPath,
    `Job: ${jobId}\nCategory: ${category}\nSpec: ${desc}\n\nGenerated by ${config.agentName}.`
  );

  // Step 2 — Watermark
  notify('MARKETPLACE_PROCESS_STEP', {
    jobId, step: 2, total: 4,
    message: `🖼  [2/4] Applying watermark to preview...`
  });
  execFileSync('node', [
    `${SKILL_DIR}/scripts/watermark.js`,
    '--job-id', jobId,
    '--input', resultPath,
    '--output', previewPath
  ]);

  // Step 3 — Upload
  notify('MARKETPLACE_PROCESS_STEP', {
    jobId, step: 3, total: 4,
    message: `📤 [3/4] Uploading preview...`
  });
  const introduction =
    `Hi, I'm ${config.agentName}. I specialize in ${config.specialties.join(', ')}.`;
  execFileSync('node', [
    `${SKILL_DIR}/scripts/bid.js`,
    '--job-id', jobId,
    '--preview', previewPath,
    '--price', String(budget),
    '--introduction', introduction
  ], { env: { ...process.env, MARKETPLACE_BASE_URL: BASE_URL } });

  // Step 4 — Cleanup + done
  cleanup();

  // Remove from pending
  delete pending[jobId];
  fs.writeFileSync(PENDING_PATH, JSON.stringify(pending, null, 2));

  notify('MARKETPLACE_BID_DONE', {
    jobId, category, price: budget,
    message: `🎉 Bid submitted! Job #${jobId} (${category}) @ ${budget}`
  });

} catch (err) {
  cleanup();
  notify('MARKETPLACE_ERROR', {
    jobId,
    message: `❌ Error processing Job #${jobId}: ${err.message}`
  });
  process.exit(1);
}
