#!/usr/bin/env node
// SECURITY MANIFEST:
//   Environment variables accessed: MARKETPLACE_BASE_URL (only)
//   External endpoints called: {BASE}/ws (Socket.IO), {BASE}/jobs/:id (read-only)
//   Local files read: ~/.openclaw/marketplace-config.json
//   Local files written: /tmp/marketplace_result_* and /tmp/preview_* (auto-deleted after bid)

'use strict';

const { io } = require('socket.io-client');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFileSync } = require('child_process');

const CONFIG_PATH = path.join(os.homedir(), '.openclaw/marketplace-config.json');
const SKILL_DIR = path.join(os.homedir(), '.openclaw/skills/agent-task-marketplace');
const BASE_URL = process.env.MARKETPLACE_BASE_URL || 'http://localhost:3000';

// --- Validate config ---
if (!fs.existsSync(CONFIG_PATH)) {
  console.error('[Marketplace] ERROR: marketplace-config.json not found. Run onboarding first.');
  process.exit(1);
}

let config;
try {
  config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
} catch (err) {
  console.error('[Marketplace] ERROR: Failed to parse config:', err.message);
  process.exit(1);
}

if (!config.agentId) {
  console.error('[Marketplace] ERROR: agentId not found. Run register.js first.');
  process.exit(1);
}

console.log(`[Marketplace] Agent    : ${config.agentName} (${config.agentId})`);
console.log(`[Marketplace] Skills   : ${config.specialties.join(', ')}`);
console.log(`[Marketplace] Budget   : ${config.maxBudget} max`);
console.log(`[Marketplace] Server   : ${BASE_URL}`);
console.log('[Marketplace] Connecting...');

// --- Socket.IO connection ---
const socket = io(BASE_URL, {
  path: '/ws',
  auth: { agentId: config.agentId },
  reconnection: true,
  reconnectionDelay: 3000,
  reconnectionDelayMax: 30000
});

socket.on('connect', () => {
  console.log('[Marketplace] ✅ Connected. Waiting for jobs...');
});

socket.on('disconnect', (reason) => {
  console.log(`[Marketplace] Disconnected: ${reason}. Reconnecting...`);
});

socket.on('connect_error', (err) => {
  console.error('[Marketplace] Connection error:', err.message);
});

// --- Heartbeat ---
socket.on('ping', () => {
  socket.emit('pong');
  console.log('[Marketplace] 💓 Heartbeat sent');
});

// --- New job handler ---
socket.on('new-job', async (job) => {
  const jobId = job._id;
  const category = job.spec?.style || job.spec?.purpose || 'unknown';
  const budget = job.spec?.budget ?? 0;

  console.log(`\n[Marketplace] 📨 New job received`);
  console.log(`  job_id  : ${jobId}`);
  console.log(`  category: ${category}`);
  console.log(`  budget  : ${budget}`);

  // Specialty check
  if (!config.specialties.includes(category)) {
    console.log(`[Marketplace] SKIP — category mismatch (${category})`);
    return;
  }

  // Budget check
  if (budget > config.maxBudget) {
    console.log(`[Marketplace] SKIP — budget exceeded (${budget} > ${config.maxBudget})`);
    return;
  }

  console.log('[Marketplace] ✅ Job accepted. Processing...');

  const resultPath = `/tmp/marketplace_result_${jobId}`;
  const previewPath = `/tmp/preview_${jobId}`;

  try {
    // Step 1. Generate result text
    const description = job.spec?.description || 'No description provided.';
    fs.writeFileSync(
      resultPath,
      `Job: ${jobId}\nSpec: ${description}\n\nGenerated by ${config.agentName}.`
    );

    // Step 2. Generate watermarked preview
    execFileSync('node', [
      `${SKILL_DIR}/scripts/watermark.js`,
      '--job-id', jobId,
      '--input', resultPath,
      '--output', previewPath
    ]);
    console.log('[Marketplace] 🖼  Preview generated');

    // Step 3. Upload preview + submit bid
    const introduction = `Hi, I'm ${config.agentName}. I can help with: ${config.specialties.join(', ')}. Here is my preview for this job.`;
    execFileSync('node', [
      `${SKILL_DIR}/scripts/bid.js`,
      '--job-id', jobId,
      '--preview', previewPath,
      '--price', String(budget),
      '--introduction', introduction
    ], { env: { ...process.env, MARKETPLACE_BASE_URL: BASE_URL } });

    // Step 4. Cleanup
    if (fs.existsSync(resultPath)) fs.unlinkSync(resultPath);
    if (fs.existsSync(previewPath)) fs.unlinkSync(previewPath);

    console.log(`[Marketplace] ✅ Bid submitted — Job #${jobId}`);

  } catch (err) {
    console.error(`[Marketplace] ERROR processing job ${jobId}:`, err.message);
    if (fs.existsSync(resultPath)) fs.unlinkSync(resultPath);
    if (fs.existsSync(previewPath)) fs.unlinkSync(previewPath);
  }
});

process.on('SIGINT', () => {
  console.log('\n[Marketplace] Shutting down.');
  socket.disconnect();
  process.exit(0);
});
